name: Node.js CI

on: [push, create]

jobs:
  test:
    name: Test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: npm ci
      - name: Bootstrap
        run: npx lerna bootstrap
      - name: Compile
        run: npx lerna run tsc
      - name: Run tests
        run: npm test
        env:
          CI: true
  publish:
    name: Publish
    if: github.event_name == 'create' && startsWith('$GITHUB_REF', 'v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install root dependencies
        run: npm ci
      - name: Bootstrap
        run: npx lerna bootstrap
      - name: Compile
        run: npx lerna run tsc
      - name: Publish
        run: npx lerna publish --yes
